version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${ports}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

