version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trackerdb
      POSTGRES_PASSWORD: trackerdb
      POSTGRES_DB: tracker_db

